version: '3'
services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./app/example/.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      
  service:
    build: app
    image: django
    volumes:
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./app/example/.env
    depends_on:
      - db
      - elasticsearch

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    depends_on:
      - service
    ports:
      - "80:80"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
        - "8080:8080"
    volumes:
        - ./openapi.yaml:/swagger/openapi.yaml
    environment:
      SWAGGER_JSON: /swagger/openapi.yaml
  
  elasticsearch:
    image: elasticsearch:7.17.6
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /opt/elasticsearch/data

  etl:
    build: postgres_to_es
    env_file:
      - ./app/example/.env
    depends_on:
      - service
      
volumes:
  postgres_volume:
  static_volume:
  media_volume:
